# Generated by Django 4.1 on 2022-12-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("-created",), "verbose_name_plural": "Products"},
        ),
    ]
